export const mainLeft: string
export const mainRight: string
export const titleSuffixSmall: string
export const headerCopyOutput: string
export const showInMenu: string
export const titleSuffixBig: string
export const title: string
export const showOutput: string
export const showInAppBar: string
